version: '3.7'

services:
  app-server:
    container_name: backend
    image: backend-img
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: parte-y-reparte

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://root:pass@mongo:27017/
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongo
  redis:
    image: redis
    ports:
      - "6379:6379"
    env_file:
      - ./src/main/resources/.env
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    depends_on:
      - mongo-express
  frontend:
    container_name: frontend
    image: frontend-img
    build:
      context: src/main/ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./src/main/ui/.env.local
    depends_on:
      - app-server
