version: '3.7'

services:
  app-server:
    container_name: backend
    image: backend-img
    build: .
    ports:
      - "8080:8080"
  next-server:
    container_name: frontend
    image: frontend-img
    build: ./src/main/ui/
    ports:
      - 3000:3000
    depends_on:
      - app-server